STP-10 /module refactor
StratusGrid/terraform-aws-lambda-event-handler-service-discovery-sync pull request #3
Opened 2022-10-24 08:52 UTC by JoseMotto-sg

## Change description

> Module refactor to be compliance with terraform automation

## Type of change
- [ ] Bug fix (fixes an issue)
- [x] New feature (adds functionality)

## Checklists

### Development

- [x] Lint rules pass locally
- [x] Application changes have been tested thoroughly
- [x] Automated tests covering modified code pass

### Security

- [x] Security impact of change has been considered
- [x] Code follows company security practices and guidelines

### Code review 

- [x] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [x] Pull request linked to task tracker where applicable

2022-10-26 11:00 UTC, DJKaswa requested changes
Please review my comment. I think we should be specific on types of resources.

2022-10-26 11:00 UTC, DJKaswa commented on inputs.tf
> +  type        = list(any)
Why aren't we using "list(string)" instead of the generic "list(any)" here? ARN should be given as string.

2022-10-28 10:13 UTC, JoseMotto-sg commented on inputs.tf
> +  type        = list(any)
Done in https://github.com/StratusGrid/terraform-aws-lambda-event-handler-service-discovery-sync/pull/3/commits/08c0f04aac7218a0127e118c36e60a9bbc22c021

2022-10-28 16:11 UTC, DJKaswa approved these changes

2022-10-28 16:11 UTC, merged